[package]
name = "hello-rest"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { version = "0.8.1", features = ["http2"] }
tokio = { version = "1.43.0", features = ["net", "rt", "rt-multi-thread", "signal"] }
